Repository ma-um/ma-um, pull requests merged in 2021-11, with the labels that each got.

#4 Feature/#1 spring boot init
  backend/auth-server/.gitignore
  backend/auth-server/build.gradle
  backend/auth-server/gradle/wrapper/gradle-wrapper.jar
  backend/auth-server/gradle/wrapper/gradle-wrapper.properties
  backend/auth-server/gradlew
  backend/auth-server/gradlew.bat
  backend/auth-server/settings.gradle
  backend/auth-server/src/main/java/com/spuit/maum/authserver/AuthServerApplication.java
  backend/auth-server/src/main/resources/application.properties
  backend/auth-server/src/test/java/com/spuit/maum/authserver/AuthServerApplicationTests.java
  backend/diary-server/.gitignore
  backend/diary-server/build.gradle
  backend/diary-server/gradle/wrapper/gradle-wrapper.jar
  backend/diary-server/gradle/wrapper/gradle-wrapper.properties
  backend/diary-server/gradlew
  backend/diary-server/gradlew.bat
  backend/diary-server/settings.gradle
  backend/diary-server/src/main/java/com/example/diaryserver/DiaryServerApplication.java
  backend/diary-server/src/main/resources/application.properties
  backend/diary-server/src/test/java/com/example/diaryserver/DiaryServerApplicationTests.java
  backend/music-server/.gitignore
  backend/music-server/build.gradle
  backend/music-server/gradle/wrapper/gradle-wrapper.jar
  backend/music-server/gradle/wrapper/gradle-wrapper.properties
  backend/music-server/gradlew
  backend/music-server/gradlew.bat
  backend/music-server/settings.gradle
  backend/music-server/src/main/java/com/example/musicserver/MusicServerApplication.java
  backend/music-server/src/main/resources/application.properties
  backend/music-server/src/test/java/com/example/musicserver/MusicServerApplicationTests.java
Labels: BE, Spring

#8 Feature/#1 django init
  .gitignore
  maum/emotion/__init__.py
  maum/emotion/admin.py
  maum/emotion/apps.py
  maum/emotion/classes.py
  maum/emotion/migrations/0001_initial.py
  maum/emotion/migrations/0002_text_result.py
  maum/emotion/migrations/__init__.py
  maum/emotion/models.py
  maum/emotion/serializers.py
  maum/emotion/tests.py
  maum/emotion/urls.py
  maum/emotion/views.py
  maum/manage.py
  maum/maum/__init__.py
  maum/maum/asgi.py
  maum/maum/settings.py
  maum/maum/urls.py
  maum/maum/wsgi.py
  maum/requirements.txt
Labels: BE, Django

#9 #9 feature: emotion algorithm
  backend/emotion-server/.gitignore
  backend/emotion-server/LICENSE
  backend/emotion-server/README.md
  backend/emotion-server/maum/emotion/__init__.py
  backend/emotion-server/maum/emotion/admin.py
  backend/emotion-server/maum/emotion/apps.py
  backend/emotion-server/maum/emotion/classes.py
  backend/emotion-server/maum/emotion/migrations/0001_initial.py
  backend/emotion-server/maum/emotion/migrations/0002_text_result.py
  backend/emotion-server/maum/emotion/migrations/__init__.py
  backend/emotion-server/maum/emotion/models.py
  backend/emotion-server/maum/emotion/serializers.py
  backend/emotion-server/maum/emotion/tests.py
  backend/emotion-server/maum/emotion/urls.py
  backend/emotion-server/maum/emotion/views.py
  backend/emotion-server/maum/manage.py
  backend/emotion-server/maum/maum/__init__.py
  backend/emotion-server/maum/maum/asgi.py
  backend/emotion-server/maum/maum/settings.py
  backend/emotion-server/maum/maum/urls.py
  backend/emotion-server/maum/maum/wsgi.py
  backend/emotion-server/maum/recommendation/__init__.py
  backend/emotion-server/maum/recommendation/admin.py
  backend/emotion-server/maum/recommendation/apps.py
  backend/emotion-server/maum/recommendation/migrations/__init__.py
  backend/emotion-server/maum/recommendation/models.py
  backend/emotion-server/maum/recommendation/serializers.py
  backend/emotion-server/maum/recommendation/tests.py
  backend/emotion-server/maum/recommendation/urls.py
  backend/emotion-server/maum/recommendation/views.py
  backend/emotion-server/maum/requirements.txt
Labels: BE, Django

#16 Feature/#9 django model loading
  src/backend/emotion-server/maum/emotion/migrations/0001_initial.py
  src/backend/emotion-server/maum/emotion/migrations/0002_diaryemotion_emotion.py
  src/backend/emotion-server/maum/emotion/models.py
  src/backend/emotion-server/maum/emotion/urls.py
  src/backend/emotion-server/maum/emotion/views.py
  src/backend/emotion-server/maum/maum/settings.py
  src/backend/emotion-server/maum/maum/urls.py
  src/backend/emotion-server/maum/recommendation/migrations/0001_initial.py
  src/backend/emotion-server/maum/recommendation/models.py
  src/backend/emotion-server/maum/recommendation/serializers.py
  src/backend/emotion-server/maum/recommendation/views.py
  src/backend/emotion-server/maum/recommendation/views.py.orig
  src/backend/emotion-server/maum/requirements.txt
Labels: documentation, BE, Django

#17 Feature/user api
  .gitignore
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  src/.idea/.gitignore
  src/.idea/aws.xml
  src/.idea/gradle.xml
  src/.idea/misc.xml
  src/.idea/modules.xml
  src/backend/.idea/.gitignore
  src/backend/.idea/aws.xml
  src/backend/.idea/compiler.xml
  src/backend/.idea/gradle.xml
  src/backend/.idea/jarRepositories.xml
  src/backend/.idea/libraries-with-intellij-classes.xml
  src/backend/.idea/misc.xml
  src/backend/.idea/modules.xml
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/AuthServerApplication.java
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/application/user/UserService.java
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/application/user/UserServiceImpl.java
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/domain/common/BaseEntity.java
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/domain/common/HashIdGenerator.java
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/domain/user/User.java
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/domain/user/UserRepository.java
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/domain/user/exception/RegisterException.java
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/domain/user/exception/UnauthorizedException.java
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/domain/user/exception/UserNotFoundException.java
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/infrastructure/domain/jpa/config/JpaAuditingConfig.java
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/web/advice/ControllerAdvice.java
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/web/aspect/AuthenticateAspect.java
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/web/aspect/AuthenticationParameter.java
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/web/controller/HelloController.java
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/web/controller/UserController.java
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/web/response/ApiResponse.java
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/web/response/user/AuthenticateResponse.java
  src/backend/auth-server/src/main/resources/application-test.yml
  src/backend/auth-server/src/main/resources/application.yml
  src/backend/auth-server/src/test/java/com/spuit/maum/authserver/application/user/UserServiceTest.java
  src/backend/auth-server/src/test/java/com/spuit/maum/authserver/domain/user/UserRepositoryTest.java
  src/backend/auth-server/src/test/java/com/spuit/maum/authserver/web/controller/UserControllerTest.java
  src/backend/auth-server/src/test/resources/application.yml
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/DiaryServerApplication.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/domain/diary/Diary.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/web/controller/DiaryController.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/web/response/ApiResponse.java
  src/backend/music-server/src/main/java/com/spuit/maum/musicserver/MusicServerApplication.java
  src/backend/music-server/src/main/java/com/spuit/maum/musicserver/domain/music/Music.java
  src/backend/music-server/src/main/java/com/spuit/maum/musicserver/web/response/ApiResponse.java
Labels: BE, Spring

#19 #18 feat: django finish
  .vscode/settings.json
  src/backend/emotion-server/maum/emotion/classes.py
  src/backend/emotion-server/maum/emotion/migrations/0001_initial.py
  src/backend/emotion-server/maum/emotion/migrations/0002_diaryemotion_emotion.py
  src/backend/emotion-server/maum/emotion/models.py
  src/backend/emotion-server/maum/emotion/serializers.py
  src/backend/emotion-server/maum/emotion/urls.py
  src/backend/emotion-server/maum/emotion/views.py
  src/backend/emotion-server/maum/recommendation/migrations/0001_initial.py
  src/backend/emotion-server/maum/recommendation/migrations/0002_alter_song_options.py
  src/backend/emotion-server/maum/recommendation/models.py
  src/backend/emotion-server/maum/recommendation/urls.py
  src/backend/emotion-server/maum/recommendation/views.py
  src/backend/emotion-server/maum/recommendation/views.py.orig
  src/backend/emotion-server/maum/requirements.txt
Labels: BE, Django

#20 Feature/#9 django model loading
  src/backend/emotion-server/maum/recommendation/models.py
  src/backend/emotion-server/maum/recommendation/serializers.py
  src/backend/emotion-server/maum/recommendation/views.py
Labels: BE, Django

#21 Feature/authorization
  .idea/compiler.xml
  .idea/libraries-with-intellij-classes.xml
  src/backend/auth-server/src/main/java/com/spuit/maum/authserver/web/controller/UserController.java
  src/backend/auth-server/src/test/java/com/spuit/maum/authserver/application/user/UserServiceTest.java
  src/backend/diary-server/build.gradle
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/domain/common/exception/UnauthorizedException.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/infrastructure/webclient/WebClientDispatcher.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/infrastructure/webclient/WebClientDispatcherImpl.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/web/aspect/AuthenticateAspect.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/web/aspect/AuthenticationParameter.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/web/controller/DiaryController.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/web/response/ApiResponse.java
  src/backend/diary-server/src/main/resources/application-test.yml
  src/backend/diary-server/src/main/resources/application.yml
  src/backend/diary-server/src/test/java/com/example/diaryserver/DiaryServerApplicationTests.java
  src/backend/diary-server/src/test/java/com/spuit/maum/diaryserver/webclient/WebClientDispatcherTest.java
  src/backend/diary-server/src/test/resources/application.yml
  src/backend/music-server/build.gradle
  src/backend/music-server/src/main/java/com/spuit/maum/musicserver/infrastructure/webclient/WebClientService.java
  src/backend/music-server/src/main/java/com/spuit/maum/musicserver/infrastructure/webclient/WebClientServiceImpl.java
  src/backend/music-server/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  src/backend/music-server/src/main/resources/application-test.yml
  src/backend/music-server/src/main/resources/application.yml
  src/backend/music-server/src/test/java/com/example/musicserver/MusicServerApplicationTests.java
  src/backend/music-server/src/test/java/resources/application.yml
Labels: BE, Spring

#23 Feature/diary write api
  .idea/compiler.xml
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/application/diary/DiaryService.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/application/diary/DiaryServiceImpl.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/domain/common/BaseEntity.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/domain/common/HashIdGenerator.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/domain/diary/Diary.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/domain/diary/DiaryRepository.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/domain/emotion/Emotion.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/infrastructure/webclient/WebClientDispatcher.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/infrastructure/webclient/WebClientDispatcherImpl.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/web/controller/DiaryController.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/web/request/Diary/DiaryEmotionCustomRequest.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/web/request/Diary/DiaryWriteRequest.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/web/response/ApiResponse.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/web/response/Diary/DiaryCalenderResponse.java
  src/backend/diary-server/src/main/java/com/spuit/maum/diaryserver/web/response/Diary/DiaryWriteResponse.java
  src/backend/diary-server/src/test/java/com/spuit/maum/diaryserver/domain/emotion/EmotionTest.java
  src/backend/music-server/src/main/java/com/spuit/maum/musicserver/domain/emotion/Emotion.java
Labels: BE, Spring
